name: Build Docker

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      version:
        description: 'Erpnext Version'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: build
      env:
        REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
        REGISTRY_PASSWD: ${{ secrets.REGISTRY_PASSWD }}
        REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      run: |
        cd $GITHUB_WORKSPACE
        sed -i '1i FROM frappe/erpnext:${{ github.event.inputs.version }}' dockerfile
        docker login -u $REGISTRY_USER -p $REGISTRY_PASSWD registry.cn-hangzhou.aliyuncs.com
        docker build -t $REGISTRY_URL/erpnext:${{ github.event.inputs.version }}_my .
        docker push $REGISTRY_URL/erpnext:${{ github.event.inputs.version }}_my
        rm -rf ~/.docker
