name: Build Docker

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      url:
        description: 'Registry URL'
        required: true
        default: ''
      version:
        description: 'Erpnext Version'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install docker
        sudo -E systemctl start docker

    - name: build
      run: |
        cd $GITHUB_WORKSPACE
        sed -i '1i FROM frappe/erpnext:${{ github.event.inputs.version }}' dockerfile
        docker build -t ${{ github.event.inputs.url }}/erpnext:my .
        docker push ${{ github.event.inputs.url }}/erpnext:my
